### ISSUE TITLE
Proyecto de Sprints ISPC : Subir Curriculum Vitae(s)

### ISSUE THREAD

**Issue by ManuelGonzalez1** [ManuelGonzalez1/Repositorio-1-ISPC-2022#6]

**Comment by dalmaponce** [comment]
Subido

**Comment by vmgith** [comment]
[cv_AliciaMontenegro.docx](https://github.com/ManuelGonzalez1/Repositorio-1-ISPCl-2022/files/9226613/cv_AliciaMontenegro.docx)
